<?php
include "conn.php";
 
error_reporting(0);
session_start();

$Filename=$_POST['Filename'];
 
$dirname="uploadfiles/SourceFiles";
$newFilePath = $dirname."/".$Filename;

$ext = pathinfo($newFilePath, PATHINFO_EXTENSION);
 
$filename=pathinfo($newFilePath, PATHINFO_FILENAME).".".$ext;

 

$ext = pathinfo($filename, PATHINFO_EXTENSION);

$JobID= GetWMSValue("Select JobID From PRIMO_Integration WHERE Filename='".$filename."'","JobId",$conWMS);


$sFilename=$filename;
   
$token = getAPIKey($GGUserName,$GGPassword,$GGProductionMode);


UploadToGoldenGate($filename,$JobID,$token,$conWMS,$sFilename);
 
 
function UploadToGoldenGate($prFilename,$prJobID,$token,$conWMS,$sFilename){

include 'Config.php';
$fields = array();
$_SESSION['token']=$token;
// files to upload
 $filenames = array($SourceFilePath.$prFilename);

$files = array();
foreach ($filenames as $f){
   $files[$f] = file_get_contents($f);
}
 
 

// URL to upload to
$url = "https://api.innodata.com/v1.1/documents";


$curl = curl_init();

$url_data = http_build_query($fields);
$ext = pathinfo($prFilename, PATHINFO_EXTENSION);

$boundary = uniqid();
$delimiter = '-------------' . $boundary;

$post_data = build_data_files($boundary, $fields, $files);

if (strtoupper($ext)=='PDF'){
  $xType='application/pdf';
}
else{
  $xType='text/'.$ext;
}


curl_setopt_array($curl, array(
  CURLOPT_URL => $url,
  CURLOPT_RETURNTRANSFER => 1,
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  //CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POST => 1,
  CURLOPT_POSTFIELDS => $post_data,
  CURLOPT_USERPWD => $token.":".$token,
  // "Authorization: Basic dXNlci1saXZlLTYzMmE1YTYzLWQ2ZDYtNDI0Ni05MWNhLWQ1NDY2MzI2OThkMzo=",
  CURLOPT_HTTPHEADER => array(
    "Content-Type: application/octet-stream; boundary=" . $delimiter,
    "X-Name: " . $prFilename,
    "X-type: ".$xType ,
    "Content-Length: " . strlen($post_data)

  ),

  
));


//
$response = curl_exec($curl);

$jobj = json_decode($response);

$ContentURI = $jobj->response->contents_uri;
$fSize = $jobj->response->size;

ExecuteQuerySQLSERVER("Update PRIMO_integration SET ContentURI='".$ContentURI."' Where JobId='".$prJobID."'",$conWMS);

// POST JOBS
// echo $ContentURI;
 
$info = curl_getinfo($curl);

 
curl_close($curl);

PostJob($token,$ContentURI,$prFilename,$fSize,$conWMS,$isImage,$prJobID);

}
function PostJob($token,$ContentURI,$filename,$fSize,$conWMS,$isImage,$prJobID){
// echo "TOKEN:".$token."<br>";
include 'Config.php';
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.innodata.com/v1.1/jobs');

curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

// CURLOPT_USERPWD => $token.":".$token,
curl_setopt($ch, CURLOPT_POST, 1);
 

  

curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"collaboration\":{\"teams\":[{\"name\":\"".$GGTeam."\",\"steps\":[\"*\"]}]},\"input_content\":{\"role\":\"input\",\"uri\":\"".$ContentURI."\"},\"metadata\":{\"mapping\":{\"high_confidence_threshold\":\"1.0\",\"qa\":{\"teams\":[]},\"taxonomy\":\"".$GGTaxonomy."\"},\"zoning\":{\"high_confidence_threshold\":\"1.0\"}},\"type\":\"data-point-extraction\",\"use_for_training\":false}");
 
    curl_setopt($ch, CURLOPT_USERPWD, $token . ":" . $token);  
    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);


    $jobj = json_decode($result);


    // $A1=explode('"id":"',$result);
    // $A2=explode('"', $A1[1]);

    // $GGJobID = $A2[0];
     
    $GGJobID = $jobj->response->id;
    


    



    ExecuteQuerySQLSERVER("Update PRIMO_integration SET GGJobID='".$GGJobID."'  Where JobId='".$prJobID."'",$conWMS);


   
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);


}
 



function reArrayFiles($file)
{
    $file_ary = array();
    $file_count = count($file['name']);
    $file_key = array_keys($file);
   
    for($i=0;$i<$file_count;$i++)
    {
        foreach($file_key as $val)
        {
            $file_ary[$i][$val] = $file[$val][$i];
        }
    }
    return $file_ary;
}
function BookFileContent($prFileName,$TLID,$conWMS){
ini_set('upload_max_filesize', '50M');
ini_set('post_max_size', '50M');
ini_set('max_input_time', 300);
ini_set('max_execution_time', 300);

$total = count($_FILES[$prFileName]['name']);

// if ($total>0) {
//   delete_directory($dirname);
//  mkdir("uploadfiles/".$TLID);
// }
// Loop through each file
for($i=0; $i<$total; $i++) {
  //Get the temp file path
  $tmpFilePath = $_FILES[$prFileName]['tmp_name'][$i];

  //Make sure we have a filepath
  if ($tmpFilePath != ""){
    //Setup our new file path

    $newFilePath = "uploadfiles/".$TLID."/". $_FILES[$prFileName]['name'][$i];
    $prFileName=$_FILES[$prFileName]['name'][$i];
     ExecuteQuerySQLSERVER("Update tblBookInfo SET BaseFile='".$prFileName."' WHERE BookID='".$TLID."'",$conWMS);
    //Upload the file into the temp dir
    if(move_uploaded_file($tmpFilePath, $newFilePath)) {
      //Handle other code here
      
      
    } 
    
  }
}
}
 


function build_data_files($boundary, $fields, $files){
    $data = '';
    $eol = "\r\n";

    $delimiter = '-------------' . $boundary;

    foreach ($fields as $name => $content) {
        $data .= "--" . $delimiter . $eol
            . 'Content-Disposition: form-data; name="' . $name . "\"".$eol.$eol
            . $content . $eol;
    }


    foreach ($files as $name => $content) {
      $fieldname='file';
        $data .= "--" . $delimiter . $eol
            . 'Content-Disposition: form-data; name="' . $fieldname . '"; filename="' . $name . '"' . $eol
            . 'Content-Type: xml/text'.$eol
            // . 'Content-Transfer-Encoding: binary'.$eol
            ;

        $data .= $eol;
        $data .= $content . $eol;
       
    }
    $data .= "--" . $delimiter . "--".$eol;


    return $data;
}
?>

<script language="javascript">
  window.location = "Registration.php?page=Acquire";
</script>
