<?php
include "conn.php";


session_start();
// error_reporting(0);
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
 
// $token=$_SESSION['token'];
$token=$_POST['token'];
$JobID=$_POST['data'];
$filename=$_POST['filename'];
 
$ext = pathinfo($filename, PATHINFO_EXTENSION);
curl_setopt($ch, CURLOPT_URL, 'https://api.innodata.com/v1.1/jobs/'.$JobID);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_USERPWD, $token . ":" . $token);  
$headers = array();
$headers[] = 'Accept: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);



$jobj = json_decode($result);
 // echo $result;

$A1 = explode('"status":"', $result);
$A2 = explode('"', $A1[1]);
$GGStatus = $A2[0];
 
curl_close($ch);

if ($GGStatus=='completed'){
	$GGProgress='100';

	 
	 $URL= $jobj->response->output_content->uri;
	 $path_parts = pathinfo($filename);
	 $nFilename=$path_parts['filename'];

	 
	  $url = $URL;
	  $start = curl_init();
	  curl_setopt($start, CURLOPT_URL, $url);
	  curl_setopt($start, CURLOPT_RETURNTRANSFER, 1);
 	  curl_setopt($start, CURLOPT_CUSTOMREQUEST, 'GET');

	  curl_setopt($start, CURLOPT_USERPWD, $token . ":" . $token);  
	  $file_data = curl_exec($start);

	  curl_close($start);
	  $file_path = 'uploadfiles/' . $nFilename . '.xml';
	  // echo $file_path;
	  $file = fopen($file_path, 'w+');
	  fputs($file, $file_data);
	  fclose($file);

	  
}
else{
	$GGProgress = $jobj->response->progress->current;

	// $A1 = explode('"current":', $result);
	// $A2 = explode(',', $A1[1]);
	//  $GGProgress =$A2[0];
}


echo $GGStatus."(".$GGProgress."%)" ;
echo $ext;
if (strtoupper($ext)=='PDF'){
UpdatePDFInfo($token,$JobID,$conWMS);

}


function UpdatePDFInfo($token,$JobID,$conWMS){

curl_setopt($ch, CURLOPT_URL, 'https://api.innodata.com/v1.1/jobs/'.$JobID.'/contents/zoning-pagesmeta-json/1');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_USERPWD, $token . ":" . $token);  
$headers = array();
$headers[] = 'Accept: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

// echo $result;

$jobj = json_decode($result);
$PDFType= 'PDF '.$jobj->PDF_type;
$PageNo= $jobj->total_pages;

 $sql = "UPDATE PRIMO_Integration SET  PageNo='".$PageNo."', DocumentType='".$PDFType."' WHERE GGJobID='".$JobID."'"; 

echo $sql;
ExecuteQuerySQLSERVER($sql,$conWMS);


}

 ?>