<?php

include "conn.php";
session_start();
$token=$_POST['data'];
$filename=$_POST['filename'];

// $isImage=$_POST['isImage'];

$isImage='No';

$JobId= $_SESSION['JobID'];
// data fields for POST request
$fields = array();
$_SESSION['token']=$token;
// files to upload
 $filenames = array("C:\\XAMPP\\htdocs\\primoiDeagen_v2.0\\uploadfiles\\SN_20200813004759.pdf");

$files = array();
foreach ($filenames as $f){
   $files[$f] = file_get_contents($f);
}
 
 

// URL to upload to
$url = "https://api.innodata.com/v1.1/documents";


$curl = curl_init();

$url_data = http_build_query($fields);
$ext = pathinfo($filename, PATHINFO_EXTENSION);

$boundary = uniqid();
$delimiter = '-------------' . $boundary;

$post_data = build_data_files($boundary, $fields, $files);

if (strtoupper($ext)=='PDF'){
  $xType='application/pdf';
}
else{
  $xType='text/'.$ext;
}


curl_setopt_array($curl, array(
  CURLOPT_URL => $url,
  CURLOPT_RETURNTRANSFER => 1,
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  //CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POST => 1,
  CURLOPT_POSTFIELDS => $post_data,
  CURLOPT_USERPWD => $token.":".$token,
  // "Authorization: Basic dXNlci1saXZlLTYzMmE1YTYzLWQ2ZDYtNDI0Ni05MWNhLWQ1NDY2MzI2OThkMzo=",
  CURLOPT_HTTPHEADER => array(
    "Content-Type: application/octet-stream; boundary=" . $delimiter,
    "X-Name: " . $filename,
    "X-type: ".$xType ,
    "Content-Length: " . strlen($post_data)

  ),

  
));


//
$response = curl_exec($curl);

$jobj = json_decode($response);

$ContentURI = $jobj->response->contents_uri;
$fSize = $jobj->response->size;

ExecuteQuerySQLSERVER("Update PRIMO_integration SET ContentURI='".$ContentURI."' Where Filename='".$filename."'",$conWMS);

// POST JOBS
// echo $ContentURI;
 
$info = curl_getinfo($curl);

//echo "code: ${info['http_code']}";

//print_r($info['request_header']);

// echo $response;

// var_dump($response);
// echo $token;

// $err = curl_error($curl);

// echo "error";
// var_dump($err);
curl_close($curl);


PostJob($token,$ContentURI,$filename,$fSize,$conWMS,$isImage);

function PostJob($token,$ContentURI,$filename,$fSize,$conWMS,$isImage){


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.innodata.com/v1.1/jobs');

curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

// CURLOPT_USERPWD => $token.":".$token,
curl_setopt($ch, CURLOPT_POST, 1);

// curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"collaboration\":{\"teams\":[{\"name\":\"Ideagen\",\"steps\":[\"*\"]}]},\"input_content\":{\"role\":\"input\",\"uri\":\"".$ContentURI."\"},\"metadata\":{\"mapping\":{\"taxonomy\":\"ideagen-taxonomy.json\"}},\"type\":\"data-point-extraction\"}");

if ($isImage=="YES"){
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"collaboration\":{\"teams\":[{\"name\":\"Ideagen\",\"steps\":[\"*\"]}]},\"input_content\":{\"role\":\"input\",\"uri\":\"".$ContentURI."\"},\"metadata\":{\"mapping\":{\"high_confidence_threshold\":\"1.0\",\"qa\":{\"teams\":[{ \"from\": \"12dd6786-8ae2-4cfe-a851-db5d506efd53\", \"to\": \"1a55360b-b09a-492a-accf-93076ce4d614\" }]},\"taxonomy\":\"ideagen-taxonomy.json\"},\"text-extraction\":{\"ocr\":true},\"zoning\":{\"high_confidence_threshold\":\"0\"}},\"type\":\"data-point-extraction\"}");


}
else{
  curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"collaboration\":{\"teams\":[{\"name\":\"Ideagen\",\"steps\":[\"*\"]}]},\"input_content\":{\"role\":\"input\",\"uri\":\"".$ContentURI."\"},\"metadata\":{\"mapping\":{\"high_confidence_threshold\":\"1.0\",\"qa\":{\"teams\":[{ \"from\": \"12dd6786-8ae2-4cfe-a851-db5d506efd53\", \"to\": \"1a55360b-b09a-492a-accf-93076ce4d614\" }]},\"taxonomy\":\"ideagen-taxonomy.json\"},\"text-extraction\":{\"ocr\":false},\"zoning\":{\"high_confidence_threshold\":\"0\"}},\"type\":\"data-point-extraction\"}");

}

// curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"collaboration\":{\"teams\":[{\"name\":\"Ideagen\",\"steps\":[\"*\"]}]},\"input_content\":{\"role\":\"input\",\"uri\":\"".$ContentURI."\"},\"metadata\":{\"mapping\":{\"high_confidence_threshold\":\"1.0\"},\"taxonomy\":\"ideagen-taxonomy.json\"},\"type\":\"data-point-extraction\"}");

// curl_setopt($ch, CURLOPT_POSTFIELDS, "{ \"collaboration\": { \"teams\": [ { \"name\": \"Ideagen\", \"steps\": [\"*\"] } ] }, \"input_content\": { \"role\": \"input\", \"uri\": \"".$ContentURI."\" }, \"metadata\": { \"mapping\": {\"high_confidence_threshold\": \"1.0\",\"qa\": { \"teams\": [] }, \"taxonomy\": \"ideagen-taxonomy.json\" }, }, \"type\": \"data-point-extraction\"}");


curl_setopt($ch, CURLOPT_USERPWD, $token . ":" . $token);  
$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);


$jobj = json_decode($result);

$GGJobID = $jobj->response->id;
 

ExecuteQuerySQLSERVER("Update PRIMO_integration SET GGJobID='".$GGJobID."' Where Filename='".$filename."'",$conWMS);


// echo $result;
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);


 }

function build_data_files($boundary, $fields, $files){
    $data = '';
    $eol = "\r\n";

    $delimiter = '-------------' . $boundary;

    foreach ($fields as $name => $content) {
        $data .= "--" . $delimiter . $eol
            . 'Content-Disposition: form-data; name="' . $name . "\"".$eol.$eol
            . $content . $eol;
    }


    foreach ($files as $name => $content) {
      $fieldname='file';
        $data .= "--" . $delimiter . $eol
            . 'Content-Disposition: form-data; name="' . $fieldname . '"; filename="' . $name . '"' . $eol
            . 'Content-Type: xml/text'.$eol
            // . 'Content-Transfer-Encoding: binary'.$eol
            ;

        $data .= $eol;
        $data .= $content . $eol;
       
    }
    $data .= "--" . $delimiter . "--".$eol;


    return $data;
}
?>