<?php
include "conn.php";
session_start();
// error_reporting(0);
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();
 
$token=$_POST['token'];
// $token='dXNlci10ZXN0LTQ3MDhiZjA5MTg4ZjRjMWYyNzIyMzIwMzU0NGZmZmY2MTcyNGEyOWM6';
$JobID=$_POST['data'];
$filename=$_POST['filename'];
 
 
curl_setopt($ch, CURLOPT_URL, 'https://api.innodata.com/v1.1/jobs/'.$JobID.'/contents/zoning-pagesmeta-json/1');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

curl_setopt($ch, CURLOPT_USERPWD, $token . ":" . $token);  
$headers = array();
$headers[] = 'Accept: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

// echo $result;

$jobj = json_decode($result);
$ext = pathinfo($filename, PATHINFO_EXTENSION);

if (strtoupper($ext)=='PDF'){
	$PDFType= 'PDF '.$jobj->PDF_type;
	$PageNo= $jobj->total_pages;

	 $sql = "UPDATE PRIMO_Integration SET  PageNo='".$PageNo."', DocumentType='".$PDFType."' WHERE GGJobID='".$JobID."'"; 

	ExecuteQuerySQLSERVER($sql,$conWMS);
	echo $PDFType;
}
else{
	 $sql = "UPDATE PRIMO_Integration SET   DocumentType='".$ext."' WHERE GGJobID='".$JobID."'"; 

	ExecuteQuerySQLSERVER($sql,$conWMS);
	echo $ext;
}

 
 ?>