..\doc2any.exe example.rtf _out_3_example.rtf.ps
..\doc2any.exe example.rtf _out_3_example.rtf.eps
..\doc2any.exe example.rtf _out_3_example.rtf.pdf
..\doc2any.exe example.rtf _out_3_example.rtf.svg
..\doc2any.exe example.rtf _out_3_example.rtf.swf
..\doc2any.exe example.rtf _out_3_example.rtf.xps
..\doc2any.exe example.rtf _out_3_example.rtf.pcl
..\doc2any.exe example.rtf _out_3_example.rtf.plt
..\doc2any.exe example.rtf _out_3_example.rtf.emf
..\doc2any.exe example.rtf _out_3_example.rtf.wmf
..\doc2any.exe example.rtf _out_3_example.rtf.jpg
..\doc2any.exe example.rtf _out_3_example.rtf.tif
..\doc2any.exe example.rtf _out_3_example.rtf.bmp
..\doc2any.exe example.rtf _out_3_example.rtf.gif
..\doc2any.exe example.rtf _out_3_example.rtf.png
..\doc2any.exe example.rtf _out_3_example.rtf.tga
..\doc2any.exe example.rtf _out_3_example.rtf.pcx

..\doc2any.exe example.doc _out_3_example.doc.ps
..\doc2any.exe example.doc _out_3_example.doc.eps
..\doc2any.exe example.doc _out_3_example.doc.pdf
..\doc2any.exe example.doc _out_3_example.doc.svg
..\doc2any.exe example.doc _out_3_example.doc.swf
..\doc2any.exe example.doc _out_3_example.doc.xps
..\doc2any.exe example.doc _out_3_example.doc.pcl
..\doc2any.exe example.doc _out_3_example.doc.plt
..\doc2any.exe example.doc _out_3_example.doc.emf
..\doc2any.exe example.doc _out_3_example.doc.wmf
..\doc2any.exe example.doc _out_3_example.doc.jpg
..\doc2any.exe example.doc _out_3_example.doc.tif
..\doc2any.exe example.doc _out_3_example.doc.bmp
..\doc2any.exe example.doc _out_3_example.doc.gif
..\doc2any.exe example.doc _out_3_example.doc.png
..\doc2any.exe example.doc _out_3_example.doc.tga
..\doc2any.exe example.doc _out_3_example.doc.pcx

..\doc2any.exe example.docx _out_3_example.docx.ps
..\doc2any.exe example.docx _out_3_example.docx.eps
..\doc2any.exe example.docx _out_3_example.docx.pdf
..\doc2any.exe example.docx _out_3_example.docx.svg
..\doc2any.exe example.docx _out_3_example.docx.swf
..\doc2any.exe example.docx _out_3_example.docx.xps
..\doc2any.exe example.docx _out_3_example.docx.pcl
..\doc2any.exe example.docx _out_3_example.docx.plt
..\doc2any.exe example.docx _out_3_example.docx.emf
..\doc2any.exe example.docx _out_3_example.docx.wmf
..\doc2any.exe example.docx _out_3_example.docx.jpg
..\doc2any.exe example.docx _out_3_example.docx.tif
..\doc2any.exe example.docx _out_3_example.docx.bmp
..\doc2any.exe example.docx _out_3_example.docx.gif
..\doc2any.exe example.docx _out_3_example.docx.png
..\doc2any.exe example.docx _out_3_example.docx.tga
..\doc2any.exe example.docx _out_3_example.docx.pcx

..\doc2any.exe example.docx _out_3_example.docx.htm
..\doc2any.exe example.docx _out_3_example.docx.mht
..\doc2any.exe example.docx _out_3_example.docx.rtf
..\doc2any.exe example.docx _out_3_example.docx.txt
..\doc2any.exe example.docx _out_3_example.docx.xml

..\doc2any.exe readme.txt _out_3_readme.txt.ps
..\doc2any.exe readme.txt _out_3_readme.txt.eps
..\doc2any.exe readme.txt _out_3_readme.txt.pdf
..\doc2any.exe readme.txt _out_3_readme.txt.svg
..\doc2any.exe readme.txt _out_3_readme.txt.swf
..\doc2any.exe readme.txt _out_3_readme.txt.xps
..\doc2any.exe readme.txt _out_3_readme.txt.pcl
..\doc2any.exe readme.txt _out_3_readme.txt.plt
..\doc2any.exe readme.txt _out_3_readme.txt.emf
..\doc2any.exe readme.txt _out_3_readme.txt.wmf
..\doc2any.exe readme.txt _out_3_readme.txt.jpg
..\doc2any.exe readme.txt _out_3_readme.txt.tif
..\doc2any.exe readme.txt _out_3_readme.txt.bmp
..\doc2any.exe readme.txt _out_3_readme.txt.gif
..\doc2any.exe readme.txt _out_3_readme.txt.png
..\doc2any.exe readme.txt _out_3_readme.txt.tga
..\doc2any.exe readme.txt _out_3_readme.txt.pcx